version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-8

    working_directory: ~/project

    steps:
      - checkout

      - run:
        name: Run Unit Tests
        command: mvn test
      - run:
        name: Generate JaCoCo Coverage Report
        command: mvn jacoco:report
          
      - run:
        name: Upload Coverage to Codecov
        command: |
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

      - run:
        name: Run Checkstyle
        command: mvn checkstyle:checkstyle

  docs-build:
    docker:
      - image: maven:3.8.4-jdk-8
    steps:
      - checkout
      - run: mvn site
      - store_artifacts:
        path: target/site/docs
  docs-deploy:
    docker:
      - image: maven:3.8.4-jdk-8
    steps:
      - checkout
      - attach_workspace:
          at: target/site/docs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "scott.auld-paszkiewicz@alumni.univ-avignon.fr"
            git config user.name "Scott"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist target/site/docs



workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
      - docs-build:
        requires:
          - build
      - docs-deploy:
        requires:
          - build
          - docs-build
