version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-8

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Run Unit Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Coverage Report
          command: mvn jacoco:report
          
      - codecov/upload:
          token: CODECOVE_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

  upload-to-codecov:
    jobs:
      - checkout 
      - codecov/upload

